### ISSUE TITLE
Scaling of circles

### ISSUE THREAD

**Issue by EriFa** [sairum/tcsBU#4]
Hi! Awesome program. I am curious though - the circles representing the haplotypes seem to scale by the diameter of the circle, rather than the area of the circle like how most people are used to seeing haplotype networks. This means that a haplotype with double the frequency is a circle with twice the diameter, but this makes the circle more than twice as large in area, Is there any way of making the circle area, rather than the circle diameter proportional to the frequency of the haplotype?
Many thanks!

**Comment by sairum** [comment]
Hi
You are right! I really don't know how this never crossed my mind! I already corrected the code in my 'local' repository to compute a radius (d3 needs a radius) of an area which is proportional to the number of haplotypes. However, since I've done other minor changes related with the data download buttons (which are still not working, eventually related with a change in browser security policies) I'll have to check again how git works just to submit this particular modification! This may take a while since I don't use git/github that much.
Best regards
Antonio

**Comment by EriFa** [comment]
Oh yay! Thank you so much Antonio, for fixing it so fast! Looks great and works wonderfully, can't wait to use it on my data. You've saved my PhD - it's so hard finding a program that will make nice looking haplotype networks!
